"""
@Time    :2019/10/8 15:48
@Author  : 梁家熙
@Email:  :11849322@mail.sustech.edu.cn
"""
import json
from tqdm import tqdm
import random
from pprint import pprint
import os
import collections
from typing import List, Dict, Tuple
import logging

from dataprocess_scripts.bioul_biaozhu import bioul_biaozhu_jieba, bioul_biaozhu_pkuseg

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
data =  {
    "abstract": "国中水务(600187)2月18日晚间公告，拟通过现金方式受让部分老股并对仁新科技增资取得仁新科技52.53%股权，交易对价金额为2.73亿元。业绩承诺方承诺标的公司在2018年-2020年度累计扣非净利润不低于1.35亿元。标的公司主要从事电子废弃物的拆解业务，交易完成后，公司业务将进一步向环保行业延伸。",
    "title": "国中水务：拟2.73亿元收购仁新科技52.53%股权",
    "fenci": [
      "国",
      "中",
      "水务",
      "：",
      "拟",
      "2",
      ".",
      "73亿元",
      "收购",
      "仁",
      "新",
      "科技",
      "52.",
      "53%",
      "股权"
    ],
    "labels": [
      "B-None",
      "I-None",
      "I-None",
      "L-None",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "U-None",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "B-None",
      "I-None",
      "L-None",
      "O",
      "O",
      "O",
      "O",
      "U-None",
      "O",
      "O",
      "O",
      "B-None",
      "B-None",
      "I-None",
      "I-None",
      "I-None",
      "I-None",
      "I-None",
      "L-None",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "B-None",
      "I-None",
      "I-None",
      "L-None",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O",
      "O"
    ]
  }

a = bioul_biaozhu_pkuseg(data, 0.9)
print(a.run())